"""
Uninstall: remove SPIDER_CTRL from the machine.

The dangerous case this module exists to avoid is deleting somebody's source
checkout. An installer clone and a development checkout look identical — both
are git repos with the same layout — so the installers drop a marker file and
only a tree carrying that marker is ever removed whole. Anything else is
treated as a working copy, and only generated artifacts are cleared.

Every path is resolved and re-checked against the root before it is touched,
and the root itself has to survive a set of sanity checks first.

Two scopes are covered:

  - The running server's own tree (`install_root()`), which is what the
    desktop page's "Danger zone" shows by default.
  - Every OTHER SPIDER_CTRL install this account can find (`find_installs`),
    for the case that matters in practice: someone ran install.sh more than
    once, or ran it before this version existed and it has no marker, and
    those trees just sit there. `plan`/`execute` both take an explicit
    `root` now so either scope goes through the identical guards.

Locations are resolved through `Path.home()` and stdlib path joins rather
than hardcoded strings, so the same code finds `~/.spider-ctrl` on macOS and
Linux and `%USERPROFILE%\\.spider-ctrl` on Windows without a platform branch.
"""

import os
import platform
import shutil
from pathlib import Path

try:
    import psutil
except Exception:  # pragma: no cover - psutil is a hard requirement at runtime
    psutil = None

# Written by install.sh / install.ps1 into the install root.
INSTALL_MARKER = ".spider-ctrl-install"

CONFIRM_PHRASE = "DELETE"

# Generated by building or running; safe to remove from any checkout.
ARTIFACT_PATHS = [
    "server/venv",
    "server/config",
    "server/certs",
    "server/.pytest_cache",
    "frontend/out",
    "frontend/node_modules",
    "frontend/.next",
    "frontend/tsconfig.tsbuildinfo",
]


def install_root() -> Path:
    """The repo root — the parent of server/."""
    return Path(__file__).resolve().parent.parent.parent


def is_managed_install(root: Path | None = None) -> bool:
    """True when this tree was created by an installer and may be removed whole."""
    return ((root or install_root()) / INSTALL_MARKER).is_file()


def _dir_size(path: Path) -> int:
    if path.is_file() or path.is_symlink():
        try:
            return path.lstat().st_size
        except OSError:
            return 0
    total = 0
    for dirpath, dirnames, filenames in os.walk(path, onerror=lambda e: None):
        for name in filenames:
            try:
                total += (Path(dirpath) / name).lstat().st_size
            except OSError:
                pass
    return total


def _root_is_sane(root: Path) -> str | None:
    """
    Reject roots that must never be deleted. Returns a reason, or None if OK.

    This is the backstop for a bug elsewhere: even if something computed a
    wrong root, these checks stop the obvious catastrophes.
    """
    root = root.resolve()
    if root == Path(root.anchor):
        return "refusing to act on the filesystem root"
    if root == Path.home().resolve():
        return "refusing to act on the home directory"
    if len(root.parts) < 3:
        return f"refusing to act on a path this shallow: {root}"
    for parent in (Path.home() / "Desktop", Path.home() / "Documents", Path.home() / "Downloads"):
        if root == parent.resolve():
            return f"refusing to act on {root}"
    if not root.exists():
        return "Already removed — nothing left at the install location."
    if not (root / "server" / "server.py").is_file():
        return f"{root} does not look like a SPIDER_CTRL tree"
    return None


def _root_is_running(root: Path) -> bool:
    """
    Best-effort: is a server currently running out of `root`?

    Uses psutil rather than `lsof`/`netstat` so the same code works on
    Windows, macOS and Linux. Two signals, either is enough:

      1. Some process's command line runs a `server.py` whose resolved path
         sits under `root`.
      2. Something is listening on 8765 and that process's executable or
         working directory sits under `root`.

    Both can raise AccessDenied on a locked-down system (SIP on macOS,
    another user's process on Linux, a restricted account on Windows) —
    treated as "unknown", not "not running", so the caller never claims a
    running server is safe to delete out from under. False negatives are
    still possible (a process a full permission check couldn't see), which
    is why the actual delete still surfaces OS-level file-in-use errors in
    `failed` rather than trusting this alone.
    """
    if psutil is None:
        return False
    root = root.resolve()

    try:
        for proc in psutil.process_iter(["cmdline"]):
            try:
                cmdline = proc.info.get("cmdline") or []
            except (psutil.NoSuchProcess, psutil.AccessDenied):
                continue
            for arg in cmdline:
                if not arg.endswith("server.py"):
                    continue
                try:
                    script = Path(arg).resolve()
                except OSError:
                    continue
                if script == root or root in script.parents:
                    return True
    except Exception:
        pass

    try:
        for conn in psutil.net_connections(kind="inet"):
            if conn.status != psutil.CONN_LISTEN or conn.laddr.port != 8765:
                continue
            if not conn.pid:
                continue
            try:
                proc = psutil.Process(conn.pid)
                candidates = [Path(proc.exe())]
                try:
                    candidates.append(Path(proc.cwd()))
                except (psutil.AccessDenied, OSError):
                    pass
                for candidate in candidates:
                    candidate = candidate.resolve()
                    if candidate == root or root in candidate.parents:
                        return True
            except (psutil.NoSuchProcess, psutil.AccessDenied, OSError):
                continue
    except Exception:
        # net_connections needs elevated privileges on some platforms
        # (notably macOS without sudo); "unknown" degrades to "not running".
        pass

    return False


def _default_scan_roots() -> list[Path]:
    """
    Where install.sh / install.ps1 put things by default, on every OS.

    Both installers resolve to the identical relative path — ".spider-ctrl"
    under the account's home directory — so one Path.home() call covers
    macOS, Linux and Windows without a platform branch. SPIDER_CTRL_HOME is
    also honoured if set for *this* process, though a value only the
    installer saw (a different shell, a past session) cannot be recovered —
    see the note in find_installs().
    """
    candidates = [Path.home() / ".spider-ctrl"]
    env_home = os.environ.get("SPIDER_CTRL_HOME")
    if env_home:
        candidates.append(Path(env_home))
    return candidates


def find_installs(extra_roots: list[str] | None = None) -> list[dict]:
    """
    Find every SPIDER_CTRL install this account can see, plus the one this
    process is running from.

    `extra_roots` lets the caller check specific paths too (the desktop page
    passes any it can name), since a custom `SPIDER_CTRL_HOME` set only at
    install time — in a different shell, in a past session — leaves no
    record anywhere on disk. There is deliberately no filesystem-wide search
    for it: scanning every directory for something that merely *looks* like
    SPIDER_CTRL risks matching an unrelated project and is slow on a large
    disk. A `server/` subdirectory containing `server.py` is required for a
    candidate to count.

    Each result carries the same shape `plan()` does, plus `is_self` for the
    tree this process is running from.
    """
    seen: dict[Path, None] = {}
    self_root = install_root().resolve()
    for candidate in [self_root, *_default_scan_roots(), *(Path(p) for p in (extra_roots or []))]:
        try:
            resolved = candidate.resolve()
        except OSError:
            continue
        seen.setdefault(resolved, None)

    results = []
    for root in seen:
        if not (root / "server" / "server.py").is_file():
            continue
        info = plan(root)
        info["is_self"] = (root == self_root)
        results.append(info)

    # The tree serving this request first, then by size — biggest to reclaim
    # the most space, which is usually what someone doing cleanup wants.
    results.sort(key=lambda i: (not i["is_self"], -i["total_bytes"]))
    return results


def plan(root: Path | None = None) -> dict:
    """
    Describe what an uninstall would remove, without removing anything.

    `root` defaults to the running server's own tree. Pass one of the paths
    from `find_installs()` to plan a *different* install instead — the same
    guards apply either way.

    `mode` is "full" for an installer-created tree, or "artifacts" for a
    working copy, where the source is left alone.
    """
    root = (root or install_root())
    problem = _root_is_sane(root)
    managed = is_managed_install(root)

    items: list[dict] = []
    if problem is None:
        if managed:
            items.append({
                "path": str(root),
                "label": "the whole install",
                "bytes": _dir_size(root),
                "exists": True,
            })
        else:
            for rel in ARTIFACT_PATHS:
                target = root / rel
                if target.exists():
                    items.append({
                        "path": str(target),
                        "label": rel,
                        "bytes": _dir_size(target),
                        "exists": True,
                    })

    notes = []
    if not managed:
        notes.append(
            "This is a working copy, not an installed one, so the source is "
            "kept. Only generated files are removed."
        )
    running = _root_is_running(root)
    is_self = root.resolve() == install_root().resolve()
    if running and not is_self:
        # Deleting the currently-running server's own tree is the normal
        # case (the Danger Zone button does exactly that), so this warning
        # is only for a *different* install found by find_installs().
        notes.append(
            "A server appears to be running from this install. Stop it "
            "first" + (
                " — Windows keeps the virtualenv's files locked while its "
                "process is alive, so the delete would fail partway through "
                "otherwise." if platform.system() == "Windows"
                else " so nothing is deleted out from under it."
            )
        )
    if platform.system() == "Windows":
        notes.append(
            "On Windows the virtualenv in use by *this* running server "
            "cannot delete itself; remove that one folder by hand afterwards."
        )
    notes.append("The pairing token is removed, so every device has to pair again.")

    return {
        "mode": "full" if managed else "artifacts",
        "managed": managed,
        "root": str(root),
        "items": items,
        "total_bytes": sum(i["bytes"] for i in items),
        "confirm_phrase": CONFIRM_PHRASE,
        "blocked": problem,
        "running": running,
        "notes": notes,
    }


def execute(confirm: str, root: Path | None = None) -> dict:
    """
    Carry out the plan for `root` (defaults to the running server's own
    tree). `confirm` must be exactly CONFIRM_PHRASE.

    Returns {ok, removed, failed, freed_bytes, shutdown, self}. `shutdown` is
    only ever true for `self` — deleting someone else's install must never
    stop *this* process. Failures are reported rather than raised: a partial
    uninstall the user can finish by hand is more useful than an exception.
    """
    if confirm != CONFIRM_PHRASE:
        return {"ok": False, "error": f"Confirmation must be exactly '{CONFIRM_PHRASE}'."}

    target_root = (root or install_root())
    current = plan(target_root)
    if current["blocked"]:
        return {"ok": False, "error": current["blocked"]}
    if not current["items"]:
        return {"ok": True, "removed": [], "failed": [], "freed_bytes": 0,
                "shutdown": False, "self": False, "note": "Nothing to remove."}

    root = target_root.resolve()
    is_self = root == install_root().resolve()
    removed, failed, freed = [], [], 0

    for item in current["items"]:
        target = Path(item["path"]).resolve()

        # Re-check containment at delete time, not just at plan time.
        if target != root and root not in target.parents:
            failed.append({"path": str(target), "error": "outside the install root"})
            continue

        try:
            if target.is_symlink() or target.is_file():
                target.unlink()
            else:
                shutil.rmtree(target, ignore_errors=False)
            removed.append(str(target))
            freed += item["bytes"]
        except Exception as exc:
            failed.append({"path": str(target), "error": str(exc)})

    return {
        "ok": not failed,
        "removed": removed,
        "failed": failed,
        "freed_bytes": freed,
        "mode": current["mode"],
        "self": is_self,
        # The desktop page shuts the server down after deleting its own
        # tree, but must never do that as a side effect of removing a
        # *different* install — the server calling this is still running
        # out of a tree that was left untouched.
        "shutdown": is_self,
    }
